#!/usr/bin/env ruby
require 'rgitflow'
require 'rgitflow/cli'
require 'rubygems'
require 'commander/import'

program :version, RGitFlow::VERSION.to_s
program :description, 'Executable wrapper for RGitFlow rake tasks.'

command :'release start' do |c|
  c.syntax      = 'rgitflow release start'
  c.description = 'Starts a release branch'
  c.action do |args, options|
    RGitFlow::CLI.execute 'bundle', 'exec', 'rake',
                          'rgitflow:release:start'
  end
end

command :'release finish' do |c|
  c.syntax      = 'rgitflow release finish'
  c.description = 'Finishes a release branch'
  c.action do |args, options|
    RGitFlow::CLI.execute 'bundle', 'exec', 'rake',
                          'rgitflow:release:finish'
  end
end

command :'hotfix start' do |c|
  c.syntax      = 'rgitflow hotfix start'
  c.description = 'Starts a hotfix branch'
  c.action do |args, options|
    if args.length == 0
      RGitFlow::CLI.execute 'bundle', 'exec', 'rake',
                            'rgitflow:hotfix:start'
    else
      RGitFlow::CLI.execute 'bundle', 'exec', 'rake',
                            'rgitflow:hotfix:start',
                            "BRANCH=#{args[0]}"
    end
  end
end

command :'hotfix finish' do |c|
  c.syntax      = 'rgitflow hotfix finish'
  c.description = 'Finishes a hotfix branch'
  c.action do |args, options|
    RGitFlow::CLI.execute 'bundle', 'exec', 'rake',
                          'rgitflow:hotfix:finish'
  end
end

command :'feature start' do |c|
  c.syntax      = 'rgitflow feature start'
  c.description = 'Starts a feature branch'
  c.action do |args, options|
    if args.length == 0
      RGitFlow::CLI.execute 'bundle', 'exec', 'rake',
                            'rgitflow:feature:start'
    else
      RGitFlow::CLI.execute 'bundle', 'exec', 'rake',
                            'rgitflow:feature:start',
                            "BRANCH=#{args[0]}"
    end
  end
end

command :'feature finish' do |c|
  c.syntax      = 'rgitflow feature finish'
  c.description = 'Finishes a feature branch'
  c.action do |args, options|
    RGitFlow::CLI.execute 'bundle', 'exec', 'rake',
                          'rgitflow:feature:finish'
  end
end

default_command :help