#!/usr/bin/env ruby
require 'thor'
require 'rgitflow'

module RGitFlowCLI
  class Feature < Thor
    include ::RGitFlow::Console

    desc 'start <name>', 'starts a feature branch named <name>'
    def start(name)
      run 'bundle', 'exec', 'rake', 'rgitflow:feature:start', "BRANCH=#{name}"
    end

    desc 'finish', 'finishes a feature branch'
    def finish
      run 'bundle', 'exec', 'rake', 'rgitflow:feature:finish'
    end
  end

  class Release < Thor
    include ::RGitFlow::Console

    desc 'start', %Q(starts a release branch named
                    #{RGitFlow::Config.options[:release]}/#{RGitFlow::VERSION.to_s})
    def start
      run 'bundle', 'exec', 'rake', 'rgitflow:release:start'
    end

    desc 'finish', 'finishes a release branch'
    def finish
      run 'bundle', 'exec', 'rake', 'rgitflow:release:finish'
    end
  end

  class Hotfix < Thor
    include ::RGitFlow::Console

    desc 'start <name>', 'starts a hotfix branch named <name>'
    def start(name)
      run 'bundle', 'exec', 'rake', 'rgitflow:hotfix:start', "BRANCH=#{name}"
    end

    desc 'finish', 'finishes a hotfix branch'
    def finish
      run 'bundle', 'exec', 'rake', 'rgitflow:hotfix:finish'
    end
  end

  class RGitFlow < Thor
    include ::RGitFlow::Console

    desc 'status', 'prints out information about which files have changed'
    def status
      run 'bundle', 'exec', 'rake', 'rgitflow:scm:status'
    end

    desc 'feature SUBCOMMAND ...ARGS', 'start or finish a feature branch'
    subcommand 'feature', Feature

    desc 'release SUBCOMMAND ...ARGS', 'start or finish a release branch'
    subcommand 'release', Release

    desc 'hotfix SUBCOMMAND ...ARGS', 'start or finish a hotfix branch'
    subcommand 'hotfix', Hotfix
  end
end

RGitFlowCLI::RGitFlow.start ARGV